

all: helloWorld factorial vcfParser

factorial:
    gcc factorial.c -std=c90 -Wall -Wpedantic -Werror -o factorial

helloWorld:
    gcc helloWorld.c -std=c90 -Wall -Wpedantic -Werror -o helloWorld

vcfParser:
    gcc vcfParser.c -std=c90 -Wall -Wpedantic -Werror -o vcfParser
